name: main

on:
    pull_request:
    push:
        branches:
            - master
            - next

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    variant:
        uses: ./.github/workflows/variant.yml

    build:
        name: build
        needs: [variant, patch]
        strategy:
            matrix:
                include: ${{ fromJson(needs.variant.outputs.result) }}
        env:
            CORE_COMPONENTS_VARIANT: ${{ matrix.variant }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: apply patch
              run: |
                  PATCH_SOURCE='variants/${{ matrix.variant }}.patch'

                  if [ -f "$PATCH_SOURCE" ]; then
                      git apply "$PATCH_SOURCE"
                  fi

            - uses: ./.github/actions/ci-setup

            - name: run build
              run: yarn build
              env:
                  BUILD_CONCURRENCY: 4

    lint:
        name: lint
        needs: [variant, patch]
        strategy:
            matrix:
                include: ${{ fromJson(needs.variant.outputs.result) }}
        env:
            CORE_COMPONENTS_VARIANT: ${{ matrix.variant }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: apply patch
              run: |
                  PATCH_SOURCE='variants/${{ matrix.variant }}.patch'

                  if [ -f "$PATCH_SOURCE" ]; then
                      git apply "$PATCH_SOURCE"
                  fi

            - uses: ./.github/actions/ci-setup

            - name: check package.json
              run: |
                  yarn check-package-json

            - name: check tsconfig
              run: |
                  yarn tsconfig check

            - name: run format
              run: |
                  yarn format

            - name: run lint
              run: |
                  yarn lint

    test:
        name: test
        needs: [variant, patch]
        strategy:
            matrix:
                include: ${{ fromJson(needs.variant.outputs.result) }}
        env:
            CORE_COMPONENTS_VARIANT: ${{ matrix.variant }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: apply patch
              run: |
                  PATCH_SOURCE='variants/${{ matrix.variant }}.patch'

                  if [ -f "$PATCH_SOURCE" ]; then
                      git apply "$PATCH_SOURCE"
                  fi

            - uses: ./.github/actions/ci-setup

            - name: setup timezone
              uses: zcong1993/setup-timezone@master
              with:
                  timezone: Europe/Moscow

            - name: build themes
              run: |
                  yarn build --scope @alfalab/core-components-themes

            - name: run test
              run: |
                  yarn test --coverage

            - name: coveralls
              uses: coverallsapp/github-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

    demo-params:
        uses: ./.github/workflows/resolve-demo-params.yml
        secrets: inherit
        with:
            dir: ${{ github.event.pull_request.number }}

    build-demo:
        needs: [variant]
        strategy:
            matrix:
                include: ${{ fromJson(needs.variant.outputs.result) }}
        uses: ./.github/workflows/build-demo.yml
        secrets: inherit
        with:
            variant: ${{ matrix.variant }}
            artifact-name: ${{ matrix.variant }}

    deploy:
        if: ${{ github.repository == 'core-ds/core-components' }}
        needs: [variant, demo-params, build-demo]
        strategy:
            max-parallel: 1
            matrix:
                include: ${{ fromJson(needs.variant.outputs.result) }}
        uses: ./.github/workflows/deploy-demo.yml
        secrets: inherit
        with:
            run-id: ${{ needs.build-demo.outputs.run-id }}
            dir: '${{ needs.demo-params.outputs.dir }}-${{ matrix.variant }}'
            variant: ${{ matrix.variant }}
            artifact-name: ${{ matrix.variant }}

    screenshot-test:
        name: screenshot test
        needs: [variant, build-demo]
        strategy:
            matrix:
                include: ${{ fromJson(needs.variant.outputs.result) }}
        env:
            CORE_COMPONENTS_VARIANT: ${{ matrix.variant }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with:
                  lfs: true

            - uses: ./.github/actions/ci-setup

            - name: download build
              uses: actions/download-artifact@v5
              with:
                  name: ${{ matrix.variant }}
                  path: build
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  run-id: ${{ needs.build-demo.outputs.run-id }}

            - name: run screenshot test
              run: |
                  yarn test:screenshots

            - uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: 'diff-${{ matrix.variant }}'
                  path: packages/**/__diff_output__/*
                  if-no-files-found: ignore

    patch:
        needs: [variant]
        strategy:
            matrix:
                include: ${{ fromJson(needs.variant.outputs.result) }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: apply patch
              run: |
                  PATCH_SOURCE='variants/${{ matrix.variant }}.patch'

                  if [ -f "$PATCH_SOURCE" ]; then
                      git apply "$PATCH_SOURCE"
                  fi

    ci-ok:
        name: ci ok
        runs-on: ubuntu-latest
        if: always()
        needs: [lint, build, build-demo, test, screenshot-test, patch]
        env:
            FAILURE: ${{ contains(join(needs.*.result, ','), 'failure') }}
        steps:
            - name: check for failure
              run: |
                  echo $FAILURE
                  if [ "$FAILURE" = "false" ]; then
                    exit 0
                  else
                    exit 1
                  fi
