name: main

on:
    pull_request:
    push:
        branches:
            - master
            - beta
            - next

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/ci-setup

            - name: run build
              run: yarn build
              env:
                  BUILD_CONCURRENCY: 4

    lint:
        name: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/ci-setup

            - name: check tsconfig
              run: |
                  yarn tsconfig check

            - name: run lint
              run: |
                  yarn lint

    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/ci-setup

            - name: setup timezone
              uses: zcong1993/setup-timezone@master
              with:
                  timezone: Europe/Moscow

            - name: run test
              run: |
                  yarn test --coverage

            - name: coveralls
              uses: coverallsapp/github-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

    build-demo:
        uses: ./.github/workflows/build-demo.yml
        secrets: inherit

    deploy:
        if: ${{ github.repository == 'hextion/core-components' }}
        needs: build-demo
        uses: ./.github/workflows/deploy-demo.yml
        secrets: inherit
        with:
            run-id: ${{ needs.build-demo.outputs.run-id }}
            dir: ${{ github.event.pull_request.number }}

    screenshot-test:
        name: screenshot test
        runs-on: ubuntu-latest
        needs: build-demo
        steps:
            - uses: actions/checkout@v4
              with:
                  lfs: true

            - uses: ./.github/actions/ci-setup

            - name: download build
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: build
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  run-id: ${{ needs.build-demo.outputs.run-id }}

            - name: run screenshot test
              shell: bash
              run: |
                  yarn test:screenshots

            - uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: diff
                  path: packages/**/__diff_output__/*
                  if-no-files-found: ignore

    ci-ok:
        name: ci ok
        runs-on: ubuntu-latest
        if: always()
        needs: [lint, build, build-demo, test, screenshot-test]
        env:
            FAILURE: ${{ contains(join(needs.*.result, ','), 'failure') }}
        steps:
            - name: check for failure
              run: |
                  echo $FAILURE
                  if [ "$FAILURE" = "false" ]; then
                    exit 0
                  else
                    exit 1
                  fi
